// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// computeSdNaive
ComplexVector computeSdNaive(ComplexVector V, NumericVector W);
RcppExport SEXP quantspec_computeSdNaive(SEXP VSEXP, SEXP WSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< ComplexVector >::type V(VSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP );
        ComplexVector __result = computeSdNaive(V, W);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
